import os

from openai import OpenAI
from dotenv import load_dotenv

## 1. Load env variables from the .env file into the py code
load_dotenv(override=True)# override=True will override the existing env variables if they are already set in the system.which means if you have already set the OPENAI_API_KEY in your system env variables, it will be overridden by the value in the .env file. This is useful for development and testing purposes, where you might want to use different API keys for different environments (e.g., development, staging, production).

## 2. read the OpenAI API Key from the env and store it
api_key = os.getenv("OPENAI_API_KEY")

## 3. Validate the API key exsists or not. if the key is missing, we raise an error immediately instead of waiting for the key to API
if not api_key:
    raise ValueError(
        "OpenAI API Key is not set. please add it to the .env file"
    )

## 4. Initialize the OpenAI Client
client = OpenAI(api_key=api_key)

## 5. Function to define the system prompt and send user questions to the LLM
def get_response(user_input):
    messages = [
        {
            "role": "system",
            "content": ("You are a helpful AI tutor. explain all the concepts around ai with following structure"
            "1. Define the concept"
            "2. Give advantages and disadvantages"
            "3. provide the working of the concept"
            "4. Give detailed real world examples"
            )
        },
        {
            "role": "user",
            "content": user_input
        }
    ]
    ## Call the OpenAI
    response = client.chat.completions.create(
        model = "gpt-4o-mini",
        messages=messages,
        temperature=0.7,
    )

    ## return the actual text generated by this model response
    return response.choices[0].message.content
